urls.py
from django.urls import path
from comments import views
from django.contrib.auth.decorators import login_required


app_name = 'comments'
urlpatterns = [
    # Adding a new comment.
    path('new/<int:content_type_id>/<int:object_id>/',
         views.CommentCreate.as_view(), name='new'),
    # Editing a comment (if there are rights for this).
    path('edit/<int:pk>/',
         login_required(views.CommentUpdate.as_view()), name='edit'),
    # Delete a comment.
    path('delete/<int:pk>/',
         login_required(views.CommentDelete.as_view()), name='delete'),
    # Reply to comment.
    path('reply/<int:pk>/', views.CommentReply.as_view(), name='reply'),
    # A page with a list of unpublished comments.
    path('unpublished/', views.UnpublishedCommentsList.as_view(),
         name='unpublished-list'),
    # Switching comment status (published/unpublished).
    path('toggle-status/<int:pk>/', views.comment_status_toggle,
         name='status-toggle'),
]

templates/comments/_comment.html
<div class="row comment" id="comment-{{ comment.id }}">
    <div class="author-info">
        <div class="comment-name">
            {% if comment.name %}
            {{ comment.name }} | {{ comment.ip_address }}
            {% else %}
            {{ comment.user }}
            {% endif %}
        </div>
        <small class="submitted">{{ comment.created }}</small>
    </div>
    <div class="body">
        {% if comment.parent %}
        <div class="blockquote">
            <div class="quote-author">{{ comment.parent.get_comment_name }} сказал(а):</div>
            {{ comment.parent.comment|striptags|truncatechars:100 }}
        </div>
        {% endif %}
        {{ comment.comment|safe|linebreaks }}
        <ul class="links">
            <li>
                <a class="{% if request.user.is_authenticated %}ajax {% endif %}button small-button"
                   href="{% url 'comments:reply' comment.pk %}">ответить</a>
            </li>
            {% if request.user.is_staff %}
            <li>
                <a class="ajax button small-button" href="{% url 'comments:edit' comment.pk %}">править</a>
            </li>
            <li>
                <a class=" button small-button" href="{% url 'comments:delete' comment.pk %}">удалить</a>
            </li>
            <li>
                <a class="button small-button" href="{% url 'comments:status-toggle' comment.pk %}?next={{ request.path }}">{% if comment.status %}снять с публикации{% else %}опубликовать{% endif %}</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

templates/comments/_form.html
{% load i18n %}
<div class="form-wraper">
    {% if parent %}
    <h2>{% trans 'Your reply' %}</h2>
    <p>{{ parent.short_comment_text }}</p>
    {% else %}
    <h2>{% trans 'Your comment for the publication' %}</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="row">
            {% if user.is_authenticated %}
            {% trans 'You are logged in as' %} <strong>{{ user.username }}</strong>
        {% endif %}
    {% for field in form %}
        <div class="field-wrapper {{ field.name }}">
            {{ field.errors  }}
            {% if field  not in form.hidden_fields %}
                {{ field.label_tag }}
            {% endif %}
            {{ field  }}
            {% if field  not in form.hidden_fields and field.help_text %}
                <p class="help">{{ field.help_text|safe  }}</p>
            {% endif %}
        </div>
    {% endfor %}
        </div>
        {% if user.is_anonymous %}
        <div class="achtung">
            {% trans 'Messages containing spam, insults or not carrying any meaning, will be deleted.' %}
        </div>
        {% endif %}
        <input class="button button-primary" type="submit" value="{% trans 'Save' %}"></form>
</div>

templates/comments/comment_add_edit.html
{% extends "base.html" %}
{% block content %}
<h1>
    <a href="{{ object.get_absolute_url }}">{{ object }}</a>
</h1>
{% include "comments/_form.html" %}
{% endblock content %}

templates/comments/comment_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h2>{% blocktrans %}Are you sure you want to delete the comment "{{ object }}"?{% endblocktrans %}</h2>
    <input type="submit" value="{% trans 'Yes, delete' %}" />
</form>
{% endblock %}

templates/comments/comments.html
<div id="comments">
    <div id="comments-header">
        <a class="button button-primary{% if request.user.is_authenticated %} ajax{% endif %}" id="comment-add-new" href="{% url 'comments:new' content_type.id object_id %}">+ добавить комментарий</a>
    </div>
    {% for comment in comments %}
        {% include 'comments/_comment.html' with comment=comment %}
    {% endfor %}
    
{% if comments.paginator.num_pages > 1 %}
    <ul class="pagination">
    {% if comments.has_previous %}
        <li><a href="?comments={{ comments.previous_page_number }}#comments">&#9668;</a></li>
        <li><a href="?comments=1#comments">1</a></li>
        {% if comments.number > 2 %}
        <li>...</li>
        {% endif %}
    {% endif %}
        <li class="active">
         {{ comments.number }}
        </li>
    {% if comments.has_next %}
        {% if comments.next_page_number != comments.paginator.num_pages %}
        <li>...</li>
        {% endif %}
        <li><a href="?comments={{ comments.paginator.num_pages }}#comments">{{ comments.paginator.num_pages }}</a></li>
        <li><a href="?comments={{ comments.next_page_number }}#comments">&#9658;</a></li>
    {% endif %}
    </ul>
{% endif %}
</div>

templates/comments/latest_comments.html
<ul class="latest-comments">
{% for comment in comments %}
<li>
    <strong class="user-name">{% if comment.user.username %}{{ comment.user.username }}
        {% else %}{{ comment.name }}{% endif %}</strong>: <a href="{{ comment.content_object.get_absolute_url }}#comments" title="{{ comment.content_object.title|truncatewords:5 }}">{{ comment.comment|truncatewords:10 }}
    </a><small>{{ comment.created }}</small>
</li>
{% endfor %}
</ul>

templates/comments/latest_commetns.html
<ul class="latest-comments">
{% for comment in comments %}
<li>
    <strong class="user-name">{% if comment.user.username %}{{ comment.user.username }}
        {% else %}{{ comment.name }}{% endif %}</strong>: <a href="{{ comment.content_object.get_absolute_url }}#comments" title="{{ comment.content_object.title|truncatewords:5 }}">{{ comment.comment|truncatewords:10 }}
    </a><small>{{ comment.created }}</small>
</li>
{% endfor %}
</ul>

templates/comments/unpub_comments.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div id="comments" class="unpublished">
    <div id="comments-header">
        <h1 class="comments title">{% trans 'Unpublished Comments' %}</h1>
    </div>
    {% for comment in comments %}
    <div id="comment-{{ comment.id }}" class="comment">
        <div class="comment-info">
        <div class="comment-object">
            {% trans 'To Publication' %}: <a href="{{ comment.content_object.get_absolute_url }}">
                <h3>{{ comment.content_object }}</h3>
            </a>
        </div>
            {{ comment.name }} | {{ comment.created }} | {{ comment.ip_address }}</div>
        <div class="body">
        {% if comment.parent %}
            <div class="blockquote">
                <div class="quote-author">{{ comment.parent.get_comment_name }} {% trans 'said' %}:</div>
                {{ comment.parent.comment|striptags|truncatechars:100 }}
            </div>
        {% endif %}
        {{ comment.comment }}
        <ul class="links">
            <li>
                <a class="button small-button ajax" href="{% url 'comments:edit' comment.pk %}?next={{ request.path }}">{% trans 'edit' %}</a>
            </li>
            <li>
                <a class="button small-button" href="{% url 'comments:delete' comment.pk %}?next={{ request.path }}">{% trans 'delete' %}</a>
            </li>
            {% if request.user.is_staff %}
                <li>
                    <a class="button small-button" href="{% url 'comments:status-toggle' comment.pk %}?next={{ request.path }}">{% if comment.status %}{% trans 'unpublish' %}{% else %}{% trans 'publish' %}{% endif %}</a>
                </li>
            {% endif %}
        </ul>
        </div>
    </div>
    {% endfor %}
{% if comments.paginator.num_pages > 1 %}
    <div class="pagination">
        <span class="step-links">
            {% if comments.has_previous %}
            <a href="?p={{ comments.previous_page_number }}#comments">{% trans 'previous' %}</a>
            {% endif %}
            <span class="current">
                {% blocktrans %}Page {{ comments.number }} from {{ comments.paginator.num_pages }}.{% endblocktrans %}
            </span>
            {% if comments.has_next %}
            <a href="?p={{ comments.next_page_number }}#comments">{% trans 'next' %}</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>
{% endblock content %}